# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - aks-dev

on:
  push:
    branches:
      - contrib
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Use the latest Node.js version

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Install Node.js dependencies
        run: |
          if [ ! -f src/Umbraco.Cms.StaticAssets/package-lock.json ]; then
            echo "package-lock.json not found, running npm install to generate it..."
            npm install --prefix src/Umbraco.Cms.StaticAssets
          else
            npm ci --no-fund --no-audit --prefer-offline --prefix src/Umbraco.Cms.StaticAssets
          fi

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8261ECDD1C74C2ABD538B1C8E7EDBD5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6184364889EB4B40A67261177631D4F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7613415765CF42EB82C864F73F3340E7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aks-dev'
          slot-name: 'Production'
          package: .

      - name: Checkout code
        uses: actions/checkout@v2
